export const CREDIT_TYPE = {
  IN: "IN",
  OUT: "OUT",
};

export const CREDIT_REASON = {
  // Entradas
  PURCHASE_CREDITS: "PURCHASE_CREDITS",
  BONUS: "BONUS",
  REFUND: "REFUND",
  ADMIN_ADD: "ADMIN_ADD",

  // Saídas
  PURCHASE_PREMIUM: "PURCHASE_PREMIUM",
  PURCHASE_DAILY_PASS: "PURCHASE_DAILY_PASS",
  CREATE_ROOM: "CREATE_ROOM",
  RENEW_ROOM: "RENEW_ROOM",
  GIFT: "GIFT",
  HIGHLIGHT_MESSAGE: "HIGHLIGHT_MESSAGE",
  HIGHLIGHT_ROOM: "HIGHLIGHT_ROOM",
  ADMIN_REMOVE: "ADMIN_REMOVE",
};

export const TRANSACTION_SOURCE = {
  USER: "USER",
  ADMIN: "ADMIN",
  SYSTEM: "SYSTEM",
};

export const PURCHASE_TYPE = {
  REAL_MONEY: "REAL_MONEY",
  CREDITS: "CREDITS",
};
