import { PURCHASE_TYPE } from "./creditConstants";

export const STORE_PRODUCTS = [
  {
    id: "pack_10",
    name: "10 Créditos",
    description: "Pacote básico.",
    price: 10,
    realPrice: 4.90,
    category: "CREDIT_PACK",
    purchaseType: PURCHASE_TYPE.REAL_MONEY,
    enabled: true,
  },
  {
    id: "pack_30",
    name: "30 Créditos",
    description: "Ideal para se destacar na multidão.",
    price: 30,
    realPrice: 10.90,
    category: "CREDIT_PACK",
    purchaseType: PURCHASE_TYPE.REAL_MONEY,
    enabled: true,
  },
  {
    id: "pack_50",
    name: "50 Créditos",
    description: "O pacote mais popular entre os usuários.",
    price: 50,
    realPrice: 15.90,
    category: "CREDIT_PACK",
    purchaseType: PURCHASE_TYPE.REAL_MONEY,
    enabled: true,
  },
  {
    id: "pack_100",
    name: "100 Créditos",
    description: "Para os verdadeiros entusiastas do PapoLivre.",
    price: 100,
    realPrice: 25.90,
    category: "CREDIT_PACK",
    purchaseType: PURCHASE_TYPE.REAL_MONEY,
    enabled: true,
  },
  {
    id: "premium_pro",
    name: "Premium Pro (7 Dias)",
    description: "Acesso VIP, crie salas e ganhe a coroa exclusiva.",
    price: 10,
    category: "SUBSCRIPTION",
    purchaseType: PURCHASE_TYPE.CREDITS,
    enabled: true,
  },
  {
    id: "effects_pass",
    name: "Passe de Efeitos (7 Dias)",
    description: "Acesso total aos efeitos visuais animados no chat.",
    price: 3,
    category: "FEATURE",
    purchaseType: PURCHASE_TYPE.CREDITS,
    enabled: true,
  },
  {
    id: "create_room",
    name: "Criar Sala (7 Dias)",
    description: "Seja proprietário da sua própria sala no PapoLivre.",
    price: 10,
    category: "ROOM",
    purchaseType: PURCHASE_TYPE.CREDITS,
    enabled: true,
  },
  {
    id: "renew_room",
    name: "Renovar Sala (+7 Dias)",
    description: "Adicione mais 7 dias de vida à sua sala existente.",
    price: 8,
    category: "ROOM",
    purchaseType: PURCHASE_TYPE.CREDITS,
    enabled: true,
  },
  {
    id: "highlight_message",
    name: "Destacar Mensagem (Minutos)",
    description: "Sua mensagem ganha destaque visual no chat por alguns minutos.",
    price: 2,
    category: "BOOST",
    purchaseType: PURCHASE_TYPE.CREDITS,
    enabled: true,
  },
  {
    id: "highlight_room",
    name: "Destacar Sala (24 Horas)",
    description: "Coloca sua sala no topo da lista por 24 horas.",
    price: 15,
    category: "BOOST",
    purchaseType: PURCHASE_TYPE.CREDITS,
    enabled: true,
  },
];
